//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGDD_Ver5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public Banner()
        {
            ImgBanner = "~/Content/images/logo.png";
        }
        public string NameBanner { get; set; }
        public string ImgBanner { get; set; }
        public string LinkBanner { get; set; }
        public string Color_BG { get; set; }
        public int ID { get; set; }
    }
}
