//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGDD_Ver5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int ID { get; set; }
        public Nullable<int> ID_Pro { get; set; }
        public Nullable<int> ID_Cart { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ProDetail ProDetail { get; set; }
    }
}
