//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGDD_Ver5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListImage
    {
        public int ID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> CmtID { get; set; }
        public string ImagePro { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Product Product { get; set; }
    }
}
